name: Deploy Resources after Release

on:
  release:
    types: [created]

jobs:
  build_and_push_docker:
    name: Build and Push Multi-Arch Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Multi-Arch Docker Image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/butlarr:latest \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/butlarr:${{ github.event.release.tag_name }} \
            --push .
